  IF("${CMAKE_SYSTEM_PROCESSOR}" MATCHES "x86")
        ENABLE_LANGUAGE(ASM_MASM)
        IF(CMAKE_ASM_MASM_COMPILER_WORKS)
                SET(MASMFound TRUE)
        ENDIF(CMAKE_ASM_MASM_COMPILER_WORKS)
  ENDIF("${CMAKE_SYSTEM_PROCESSOR}" MATCHES "x86")

  # no assembler found
  IF(NOT MASMFound)
        MESSAGE(STATUS NOT)
  ENDIF(NOT MASMFound)
  SET(ASM_DIALECT "_MASM")

  # if we are using the 64bit cl compiler, assume we also want the 64bit assembler
  IF(CMAKE_CL_64)
    MESSAGE(STATUS MASM 64 bit)
    SET(CMAKE_ASM${ASM_DIALECT}_COMPILER_INIT ml64)
  ELSE(CMAKE_CL_64)
    MESSAGE(STATUS MASM 32 bit)
    SET(CMAKE_ASM${ASM_DIALECT}_COMPILER_INIT ml)
  ENDIF(CMAKE_CL_64)
